---
title: "Assignment 5"
author: "Khutso Ledwaba"
date: "2022-12-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Calling the cereals data file and organization
```{r}

Cereals <- read.csv(file = 'Cereals.csv') 
Cereals
str(Cereals)
head(Cereals)

Cereals = Cereals[-which(is.na(Cereals$carbo)),]
	Cereals = Cereals[-which(is.na(Cereals$potass)),]
	Cereals
	
	# Make row names the names of the utilities, remove numerical labeling of rows
	row.names(Cereals) <- Cereals[,1]
	
	Cereals <- Cereals[,-1]
	Cereals
	#Removing the mfr column
	Cereals <- Cereals[,-1]
	Cereals
	#Removing the type column
	Cereals <- Cereals[,-1]
	Cereals
```

##Question 1 Calculating the euclidean distance
```{r}	
	
	# normalization of the input variables
	Cereals.norm <- sapply(Cereals, scale)
	
	# add row names to Cereals
	row.names(Cereals.norm) <- row.names(Cereals)
	
	# Calculation of the euclidean distance
	d.norm <- dist(Cereals.norm, method = "euclidean")
```

#Question 2 and 3 working with clusters
```{r}	
	# Scatter plot
	CerealsKM<-kmeans(Cereals.norm, 6)
	#there are 6 clusters
	
	plot(c(0), xaxt = 'n', ylab = "", type = "l", ylim = 
	       c(min(CerealsKM$centers), max(CerealsKM$centers)), xlim = c(0, 8))
	
	# label x-axes
	axis(1, at = c(1:13), labels = names(Cereals))
	
	# Graph plot
	for (i in c(1:6))
	  lines(CerealsKM$centers[i,], lty = i, lwd = 2, col = ifelse(i %in% c(1, 3, 5),"black", "blue"))
	
	# name clusters
	text(x = 0.5, y = CerealsKM$centers[, 1], labels = paste("Cluster", c(1:6)))
	
	#averages of the clusters for each variable
	CerealsKM$centers
	
	#distance between points of the clusters
	CerealsKM$withinss
	
	#The size of the cluster
	CerealsKM$size
	
	#Calculating the distance between the points of each cluster
	wss <- numeric(6)
	
	#The mean of the distance between points within a cluster vs number of clusters
	for (k in 1:6) wss[k] <- mean(kmeans(Cereals.norm, centers = k, nstart = 25)$withinss)
	plot(1:6, wss, type="b",xlab="Number of Clusters", ylab="Within Sum of Squares")
	
	#SINGLE CLUSTER
	hc1 <- hclust(d.norm, method = "single")
	hc1
	
	plot(hc1, hang = -1, ann = FALSE)
	
	#Display 6 clusters
	cutree(hc1,k=6)
  #Display 10 clusters
	cutree (hc1, k=10)

	
	#COMPLETE CLUSTER
	hc2 <- hclust(d.norm, method = "complete")
	hc2
	
	plot(hc2, hang = -1, ann = FALSE)
	
	
	#Display 2 clusters
	cutree(hc2,k=2)
	
	#Displaying the 6 clusters
	cutree (hc2, k=5)
```
	
	
##Question 4	
```{r}

	#This shows that the data should not be normalized. The cluster for the healthy cereals should be arranged so that the schools can offer a different version cereal each day which would be the best option.
```